"""empty message

Revision ID: f03fe7b9ada2
Revises: f91c7bfc0b07
Create Date: 2023-03-22 09:13:43.013724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03fe7b9ada2'
down_revision = 'f91c7bfc0b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], onupdate='cascade', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], onupdate='cascade', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_Venue', sa.Boolean(), nullable=True))
        batch_op.drop_column('seeking_venue')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('seeking_Venue')

    op.drop_table('Show')
    # ### end Alembic commands ###
